### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by vaghawan** [upasch/g5-chatbot-ui#1]
Hi, 

Thanks for this project, one thing, how can we sign in? There seems no option to register at the first place. For example, if you go here, https://g5-chatbot-ui.vercel.app/ , which credential should be used to login this page? 

Thanks
V

**Comment by upasch** [comment]
Hi, you can’t login on that project. You first need to fork the code into your own repo and provide your own keys for OpenAI and Supabase.

**Comment by vaghawan** [comment]
Got it, Thank you
